config/routes.rb
TweetBookOnRails::Application.routes.draw do
  
  post 'pusher/auth'
  
  get "sessions/new"

  get 'errores/error404'
  get 'errores/error500'
  get 'errores/raise500'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions,      :only => [:new, :create, :destroy]
  resources :microposts,    :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  
  root :to => 'pages#home'
  match '/prezi', :to => 'pages#prezi'
  match '/signup', :to => 'users#new' 
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/faq', :to => 'pages#faq'
  match '/profile', :to => 'users#show'
  match '/cuenta', :to => 'pages#cuenta'
  match '/help', :to => 'pages#help'
  match 'about', :to => 'pages#about'
  match '*not_found', :to => 'errores#error404'
  
  
    

end

app/models/user.rb
# -*- encoding : utf-8 -*-
# == Schema Information
#
# Table name: users
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime
#  updated_at :datetime
#
require 'digest'

class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation, :identity, :desc, :avatar
  
  has_many :microposts, :dependent => :destroy
  has_many :reverse_relationships, :foreign_key => "followed_id",
                                   :class_name => "Relationship",
                                   :dependent => :destroy
  has_many :followers, :through => :reverse_relationships, :source => :follower
  has_many :relationships, :foreign_key => "follower_id",
                           :dependent => :destroy
  has_many :following, :through => :relationships, :source => :followed
  
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates :name, :presence => true,
                   :length => { :maximum => 50 }
  validates :email, :presence => true,
                   :format => { :with => email_regex },
                   :uniqueness => { :case_sensitive => false}
  validates :password, :presence     => true,
                       :confirmation => true,
                       :length       => { :within => 6..40 } 
  validates :identity, :presence => true,
                   :length => { :maximum => 50 },
                   :uniqueness => { :case_sensitive => false}
  validates :desc, :length => { :maximum => 200 }
                       
  before_save :encrypt_password
  
  has_attached_file :avatar, :styles => { :medium => "128x128>", :thumb => ["50x50#", :png ], :mini => ["30x30#", :png] }, :default_url => "/images/NoImage.png"
  
  def feed
    Micropost.from_users_followed_by(self)
  end
  
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end
  
  def self.authenticate email, submitted_password
    user = find_by_email email
    return nil if user.nil?
    return user if user.has_password? submitted_password
  end
  
  def following?(followed)
      relationships.find_by_followed_id(followed)
  end

  def follow!(followed)
      relationships.create!(:followed_id => followed.id)
  end
  def unfollow!(followed)
      relationships.find_by_followed_id(followed).destroy
  end
  
  private
  
    def encrypt_password
      self.salt = make_salt unless has_password?(password)
      self.encrypted_password = encrypt(password)
    end
                   
    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end
    
    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end
    
    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
  
    def self.authenticate(email, submitted_password)
      user = find_by_email(email)
      return nil if user.nil?
      return user if user.has_password?(submitted_password)
    end
    
    def self.authenticate_with_salt(id, cookie_salt)
      user = find_by_id(id)
      (user && user.salt == cookie_salt) ? user : nil
    end 
   
      
end

app/controllers/users_controller.rb
# -*- encoding : utf-8 -*-
class UsersController < ApplicationController
  before_filter :authenticate , :except => [:new, :create]
  before_filter :correct_user, :only => [:edit, :update]
  before_filter :admin_user,   :only => :destroy
  
  def new
    @title = "Sign up"
    @user = User.new
  end
  
  def index
    @title = "Usuarios"
    @users = User.paginate(:page => params[:page])
  end
  
  def show
    @user = User.find(params[:id]) if params[:id]
    @user = current_user if (signed_in? && request.url =~ /profile/) 
    @microposts = @user.microposts.paginate(:page => params[:page])
    @micropost = Micropost.new
    @title = @user.name + " - Perfil"
    respond_to do |format|
      format.html
      format.js   
    end   
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      UserMailer.welcome_email(@user).deliver
      sign_in @user
      flash[:success] = "Bienvenido a TweetBook"
      redirect_to @user
    else
      @title = "Sign up"
      #redirect_to '/signup'
      render 'new'
    end    
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_path
  end
  
  def edit 
    @title = "Configurar"
  end
  
  def update
    @user = User.find(params[:id])
    if params[:user][:password].blank? || params[:user][:password_confirmation].blank?
      params[:user].delete :password
      params[:user].delete :password_confirmation
    end
    if @user.update_attributes(params[:user])
      flash[:success] = "Perfil actualizado."
      redirect_to @user
    else
      @title = "Edit user"
      render 'edit'
    end
  end
  
  def following
    @title = "Following"
    @user = User.find(params[:id])
    @micropost = Micropost.new if signed_in?
    @users = @user.following.paginate(:page => params[:page])
    #render 'show_follow'
    respond_to do |format|
      format.html { render 'show' }
      format.js
    end    
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @micropost = Micropost.new if signed_in?
    @users = @user.followers.paginate(:page => params[:page])
    #render 'show_follow'
    respond_to do |format|
      format.html { render 'show' }
      format.js
    end   
  end
  
  private
    
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
  
end

app/helpers/users_helper.rb
# -*- encoding : utf-8 -*-
module UsersHelper
  def gravatar_for(user, options = { :size => :thumb })
    
    classes = 'gravatar'
    classes += " thumb" if (user.avatar.url(options[:size]) =~ /NoImage\.png/i) && (options[:size] == :thumb)
    classes += " mini" if (user.avatar.url(options[:size]) =~ /NoImage\.png/i) && (options[:size] == :mini)
    image_tag user.avatar.url(options[:size]), :alt => h(user.name), :class => classes
    #"#{classes} -- #{user.avatar.url(options[:size])}"
    
    #gravatar_image_tag(user.email.downcase, :alt => h(user.name), :class => 'gravatar', :gravatar => options)
  end
  
  def link_to_identity(identity)
    path = User.find_by_identity(identity) || root_path
    link_to "@#{identity}",path
  end
  
end

app/views/users/_follow.html.erb
<%= form_for current_user.relationships.
                          build(:followed_id => @user.id), :remote => true do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <div class="actions"><%= f.submit "Seguir", :class => "btn btn-primary tweetBookButton" %></div>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_show_follow.html.erb
<table summary="Information about following/followers">
  <tr>
    <td class="main">

      <% unless @users.empty? %>
        <ul class="users">
          <%= render @users %>
        </ul>
        <%= will_paginate @users, :renderer => BootstrapPagination::Rails %>
      <% end %>
    </td>
  </tr>
</table>

app/views/users/_unfollow.html.erb
<%= form_for current_user.relationships.find_by_followed_id(@user),
             :html => { :method => :delete }, :remote => true do |f| %>
  <div class="actions"><%= f.submit "Dejar de seguir", :class => "btn btn-primary tweetBookButton" %></div>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, :size => :mini %>
  <%= link_to user.name, user %>
  <% if current_user.admin? %>
  | <%= link_to "Borrar", user, :method => :delete, :confirm => "You sure?",
                                :title => "Delete #{user.name}" %>
  <% end %>
  <%= "\"" + user.desc + "...\"" if user.desc %>
</li>

app/views/users/edit.html.erb
<div id="editProfile" class="span11 mainContainer">
	<div class="row-fluid">
		<div class="span4">
			<div class="well">
				<div class="userInfo row-fluid">
					<div class="userAvatar span1">
						<%= gravatar_for current_user, :size => :thumb%>
					</div>
					<div class="userName span3 offset1">
						<%= current_user.name %><br/>
						<small class="more">Ver mi página de perfil</small>
					</div>					
				</div>
			</div>				
		</div>
		<div class="span7 offset4 well">
			<h1 class="title">Cuenta</h1>
			<span class="desc">Cambia tu configuración de cuenta básica.</span>
			<%= form_for(@user,:html => {:multipart => true}) do |f| %>
		  		<%= render 'shared/error_messages', :object => f.object %>
			  	<div class="field">
			    	<%= f.label :name, "Nombre" %>
			    	<%= f.text_field :name %>
			  	</div>
			  	<div class="field">
			    	<%= f.label :email %>
			    	<%= f.text_field :email %>
			  	</div>
			  	<div class="field">
			    	<%= f.label :identity, "Usuario" %>
			    	<%= f.text_field :identity %>
			  	</div>
			  	<div class="field">
			  		<%= f.label :desc, "Descripción" %>
			    	<%= f.text_area :desc %>
			  	</div>
			  	<div class="field">
			    	<%= f.label :password, "Contraseña" %>
			    	<%= f.password_field :password %>
			  	</div>
			  	<div class="field">
			    	<%= f.label :password_confirmation, "Confirmacion" %>
			    	<%= f.password_field :password_confirmation %>
			  	</div>
			  	<div class="field">
			  	  	<%= gravatar_for @user %>
	  				<!--<a href="http://gravatar.com/emails">Cambiar</a>-->
	  				<%= f.file_field :avatar%>
  				</div>
			  	<div class="actions">
			    	<%= f.submit "Actualizar" %>
			  	</div>
			<% end %>			
		</div>			
	</div>
</div>

<!--<h1>Edit user</h1>

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

<div>
  <%= gravatar_for @user %>
  <a href="http://gravatar.com/emails">change</a>
</div>-->

app/views/users/followers.js.erb
$(".timeLine").html("<%= escape_javascript(render('users/show_follow')) %>")
$(".timeLine").prepend('<h1 class="feedTitle"><%=@title%></h1>')

app/views/users/following.js.erb
$(".timeLine").html("<%= escape_javascript(render('users/show_follow')) %>")
$(".timeLine").prepend('<h1 class="feedTitle"><%=@title%></h1>')

app/views/users/index.html.erb
<div id="users" class="span11 mainContainer">
	<div class="row-fluid">
		<div class="leftBar span4">
			<div class="well">
				<h4>Personas en nuestra comunidad </h4>
				<div class="Numero">
					<%= @users.count %>
				</div>
			</div>
			<div class="well">
				<div class="userInfo row-fluid">
					<div class="userAvatar span1">
						<%= gravatar_for current_user, :size => :thumb%>
					</div>
					<div class="userName span3 offset1">
						<strong><%= current_user.name %></strong><br/>
						<small class="more"><a href="<%= user_path(current_user)%>">Ver mi página de perfil</a></small>
					</div>
				</div>
				<%= render 'shared/stats'%>
			</div>
		</div>
		<div class="timeLine span7 offset4 well">
			<h1 class="feedTitle">Usuarios</h1>
			<ul class="users">
				<%= render @users %>
			</ul>
			<%= will_paginate :renderer => BootstrapPagination::Rails %>
		</div>
	</div>
</div>

app/views/users/new.html.erb
<div id="signup-wrapper">
	<h1>Sign up</h1>
	
	<%= form_for(@user) do |f| %>
		<%= render 'shared/error_messages', :object => f.object %>
	  <div class="field">
	    <%= f.label :name, "Nombre" %>
	    <%= f.text_field :name, :placeholder => "Nombre completo" %>
	  </div>
	  <div class="field">
	    <%= f.label :email, "Email" %>
	    <%= f.text_field :email, :placeholder => "Correo electrónico" %>
	  </div>
	  <div class="field">
	    <%= f.label :identity, "Nombre usuario" %>
	    <%= f.text_field :identity, :placeholder => "Nombre usuario" %>
	  </div>
	  <div class="field">
	    <%= f.label :password, "Contraseña" %>
	    <%= f.password_field :password, :placeholder => "Contraseña" %>
	  </div>
	  <div class="field">
	    <%= f.label :password_confirmation, "Confirmación" %>
	    <%= f.password_field :password_confirmation, :placeholder => "Confirmación" %>
	  </div>
	  <div class="actions">
	    <%= f.submit "Registrar" %>
	  </div>
	<% end %>
</div>

app/views/users/show.html.erb
<div id="profile" class="span11 mainContainer">
	<div class="userInfo well">
		<div class="row-fluid">
			<div class="span2">
				<%= gravatar_for @user, :size => :medium %>
			</div>
			<div class="status span7 offset3">
				<h1><%= @user.name %></h1>
				<p class="userName">@<%= @user.identity %></p>
				<p class="bio"><%= @user.desc%></p>
			</div>
			<div class="operations offset8 span2">
				<p>
					<% if current_user?(@user)%>
						<%= link_to "Configuración", edit_user_path(current_user), :class => "btn btn-primary tweetBookLink"%>
					<% else %>
						<%= render 'follow_form' if signed_in? %>
					<% end%>
				</p>
	        	<!--<p><%= link_to user_path(@user), @user %></p>-->
	        	<p><%= pluralize(@user.microposts.count,"micropost") %></p>
	        	<p><%=@user.followers.count%> seguidores</p>
	        	<p><%=@user.following.count%> siguiendo</p>
			</div>
        </div>	
	</div>	
	<div class="row-fluid">
		<div class="leftBar span4">
			<div class="well">
				<ul class="nav nav-pills nav-stacked">
					<li <%='class=active' if @title =~ /Perfil/%>><%= link_to "Cronología", @user, :remote => "true" %></li>
					<li <%='class=active' if @title =~ /Followers/%>><a href="<%= followers_user_path(@user) %>" data-remote="true">Seguidores</a></li>
					<li <%='class=active' if @title =~ /Following/%>><a href="<%= following_user_path(@user) %>" data-remote="true">Siguiendo</a></li>
				</ul>
			</div>
			<div class="well">
				<%= render "shared/similares"%>
			</div>
		</div>
		<div class="timeLine span7 offset4 well">
			<h1 class="feedTitle"><%=@title%></h1>
			<% if @title =~ /Perfil/%>
		      <% if !@user.microposts.empty? %>
		          <%= render @microposts %>
		        <%= will_paginate @microposts, :renderer => BootstrapPagination::Rails %>
	       	  <% else %>
	       	  	<p>Todavía no <% if current_user?(@user)%> has <% else %> ha <% end %> publicado nada.</p>
		      <% end %>
	      	<%else%>
      		  <%=render 'show_follow'%>
	      	<% end %>
		</div>    
		<%=render 'shared/delete_tweet'%>
		<%=render 'shared/reply_tweet'%>
	</div>
</div>

app/views/users/show.js.erb
  <% if !@user.microposts.empty? %>
  	<% content =  render(@microposts) %>
  	<% content += will_paginate(@microposts, :renderer => BootstrapPagination::Rails)%>
  	$(".timeLine").html("<%=escape_javascript(content)%>")
  <% else %>
  	$(".timeLine").html('<p>Todavía no <% if current_user?(@user)%> has <% else %> ha <% end %> publicado nada.</p>')
  <% end %>
$(".timeLine").prepend('<h1 class="feedTitle"><%=@title%></h1>')