config/routes.rb
TweetBookOnRails::Application.routes.draw do
  
  post 'pusher/auth'
  
  get "sessions/new"

  get 'errores/error404'
  get 'errores/error500'
  get 'errores/raise500'

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions,      :only => [:new, :create, :destroy]
  resources :microposts,    :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  
  root :to => 'pages#home'
  match '/prezi', :to => 'pages#prezi'
  match '/signup', :to => 'users#new' 
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/faq', :to => 'pages#faq'
  match '/profile', :to => 'users#show'
  match '/cuenta', :to => 'pages#cuenta'
  match '/help', :to => 'pages#help'
  match 'about', :to => 'pages#about'
  match '*not_found', :to => 'errores#error404'
  
  
    

end

app/views/layouts/_footer.html.erb
<div id="footer" class="span11 mainContainer">
	<div class="row-fluid">
		<div class="span11">
		  <ul>
		    <li><a href="/about">Sobre nosotros</a><span class="dot divider"> &middot;</span></li>
		    <li><a href="/faq">Ayuda</a><span class="dot divider"> &middot;</span></li>
		    <li><a href="http://github.com/tagoro9/TweetBook-on-Rails" alt="Proyecto en github">Sigue el proyecto</a></li>
			<li><span class="copyright">© <%=Time.now.year%> TweetBook</span></li>
		  </ul>
		</div>
	</div>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<img id="brandImg" src="/images/Icono.png" alt="icono"/>
			<a class="brand" href="<%= root_path %>">TweetBook</a>
			<nav class="nav-collapse">
				<ul class="nav">
					<li class="<%= "active" if @title =~ /Home/ %>"><%= link_to "Home", root_path %></li>
					<% if signed_in? %>
						<li class="<%= "active" if @title == 'Usuarios'%>"><%= link_to "Usuarios", users_path %></li>
						<li class="<%= "active" if @title =~ /Perfil|Following|Followers|Configurar/%>"><%= link_to "Perfil", profile_path %></li>
					<% end %>
					<li class="<%= "active" if @title == 'Ayuda'%>"><%= link_to "Ayuda", help_path %></li>		
					<% if signed_in? %>
						<li><%= link_to "Sign out", signout_path, :method => :delete %></li>
					<% else %>
						<li><%= link_to "Sign in", signin_path %></li>
					<% end %>					
				</ul>
				<% if signed_in? %>
					<ul class="nav pull-right">
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">Cuenta<b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li class="nav-header">Opciones</li>
								<li class="divider"></li>
								<li><%= link_to "Configurar", edit_user_path(current_user)%></li>
							</ul>
						</li>
					</ul>
				<% end %>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/_login_footer.html.erb
<div class="footer inline-list">
  <ul>
    <li><a href="/about">Sobre nosotros</a><span class="dot divider"> &middot;</span></li>
    <li><a href="/faq">Ayuda</a><span class="dot divider"> &middot;</span></li>
    <li><a href="http://github.com/tagoro9/TweetBook-on-Rails" alt="Proyecto en github">Sigue el proyecto</a></li>
	<li><span class="copyright">© <%=Time.now.year%> TweetBook</span></li>
  </ul>
</div>

app/views/layouts/_login_header.html.erb
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <img id="brandImg" src="/images/Icono.png" alt="icono"/>
          <a class="brand" href="<%= root_path %>">TweetBook</a>
          <% if !/Inicio|Sign\sin/.match @title%>
			<%=form_for(:session, :url => sessions_path, :html => {:id => 'loginArriba',:class => 'navbar-form pull-right'}) do |f| %>			
			  		<%= f.text_field(:email, :placeholder => 'Email') %>
				  	<%= f.password_field(:password, :placeholder => 'Contraseña') %>
				  	<%= f.submit("Entrar", :class => 'btn btn-primary tweetBookButton', :id => 'entrarArriba') %>
			<% end %>			
          <% end%>
          <!--<div class="nav-collapse">
            <ul class="nav">
            </ul>
          </div>--><!--/.nav-collapse -->
        </div>
      </div>
    </div>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'bootstrap/css/bootstrap', :media => 'screen' %>
<%= stylesheet_link_tag 'estilo', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
  		<title>TweetBook | <%= @title %></title>
  		<link rel="shortcut icon" href="/images/favicon.ico" type="image/x-icon"/>
		<%= csrf_meta_tag %>
		<%= render 'layouts/stylesheets' %>
    	<%= javascript_include_tag :defaults %>
    	<script src="http://js.pusherapp.com/1.9/pusher.min.js"></script>
	</head>
	<body class="<%= bodyClass %>">
		<div id="statusPusher"></div>
		<input type="hidden" id="user_id_pusher" value="<%= current_user.id if signed_in? %>"/>
		<div class="container" id="content">
			<%= header %>
			<div class="flash" id="notifications">
				
			</div>
			<div class="flash">
				<% flash.each do |key, value| %>
					<div class="alert alert-<%= key %>">
						<a class="close" data-dismiss="alert" href="#">×</a>
						<%= value %>
					</div>
				<% end %>			
			</div>
			<%= yield %>
			<%=render 'shared/new_tweet' if signed_in? && @micropost%>
			<%= footer %>
			<!--<%= debug(params) if Rails.env.development? %>-->
		</div>		
	</body>
</html>